package com.example.mvvminfo.ShowData.model

import java.io.Serializable

class ShowResponse : ArrayList<ShowResponseItem>()

data class ShowResponseItem(
    val Age: String,
    val AgeDays: Int,
    val AgeMonth: Int,
    val AgeYear: Int,
    val Alternatemobileno: String,
    val AppLatitude: Double,
    val AppLongitude: Double,
    val CentreID: Int,
    val City: String,
    val CityID: Int,
    val Client: String,
    val DOB: String,
    val DoctorID: Int,
    val Gender: String,
    val HardCopyRequired: Int,
    val House_No: String,
    val IsCouponEntry: Int,
    val IsDOBActual: Int,
    val IsPaid: Int,
    val IsPermanentAddress: Int,
    val IsPreprinterbarcode: Int,
    val IsPrimaryMember: Int,
    val IsRateFromAPI: String,
    val Locality: String,
    val LocalityID: Int,
    val Mobile: String,
    val OneApolloPoint: Double,
    val OtherDoctor: String,
    val PName: String,
    val Panel_ID: Int,
    val Patient_ID: String,
    val Paymentmode: String,
    val PhlebotomistID: Int,
    val Pincode: String,
    val PreBookingID: String,
    val PreBookingID_Primary: String,
    val PrebookingIDAPI: String,
    val ReceiptRequired: Any,
    val ReferRatePanelID: Int,
    val ReferedDoctor: String,
    val Remarks: String,
    val SourceofCollection: String,
    val State: String,
    val StateID: Int,
    val Status: String,
    val TestDetail: List<TestDetail>,
    val Title: String,
    val TotalAgeInDays: Int,
    val VIP: Int,
    val VerificationCode: String,
    val appdatetime: String,
    val centre: String,
    val landmark: String
):Serializable

data class TestDetail(
    val DiscAmt: Double,
    val DiscountApplicable: Int,
    val IsDeliveryCharge: Int,
    val ItemName: String,
    val ItemType: String,
    val NetAmt: Double,
    val PackageItemId: String,
    val PackageItemName: String,
    val Rate: Double,
    val SampleTypeName: String,
    val SubCategoryID: Int,
    val TestCode: String,
    val itemid: Int
):Serializable